In [43]:
import numpy as np

In [36]:
w = np.array([2,2,2,2]) #one dimensional array


print(total)

8


In [87]:
30 ** 0.5

5.477225575051661

In [96]:
#w.sum() Q1 ANSWER
#Q2 ANSWER
L2norm=np.sum(np.square(w))
L2norm=np.sqrt(L2norm)
print(L2norm)

5.47722557505


In [48]:
L2norm = 0

for i in range(w.shape[0]):

    L2norm += w[i] ** 2

L2norm = L2norm ** 0.5

L2norm

4.0

In [ ]:

X.shape = (6,4) 
X.shape returns (6,4)
colsum = np.zeros(X.shape[1])

In [295]:
X = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
w = np.array([1,2,3,4])
y = np.array([1,2,3,4,5,6])
y_pred = 1
hingeloss = 0 
y_pred = y_pred+np.sum(w*X,axis=1)
hingeloss=hingeloss+y[y-y_pred>0]
hingeloss = np.sum(hingeloss)
print(hingeloss)

0


In [293]:
hingeloss = 0

for i in range(X.shape[0]):

    y_pred = 1

    for j in range(X.shape[1]):

        y_pred += w[j] * X[i, j]

    if y[i] - y_pred > 0:

        hingeloss += y[i] - y_pred
hingeloss

0

In [280]:
grd = np.zeros(w.shape[0])

yhat = np.ones(X.shape[0]) * 1

for i in range(X.shape[0]):

    for j in range(X.shape[1]):

        yhat[i] += w[j] * X[i,j]

for j in range(X.shape[1]):

    for i in range(X.shape[0]):

        grd[j] += (y[i] - yhat[i]) * X[i][j]

grd






array([-165., -330., -495., -660.])

In [263]:
loss = 0

for i in range(X.shape[0]):

    y_pred = 1

    for j in range(X.shape[1]):

        y_pred += w[j] * X[i, j]

    loss += (y[i] - y_pred) ** 2   

print(loss)
print(y_pred)

4555
31


In [242]:
score = np.ones(X.shape[0]) * 1
for i in range(X.shape[0]):

    for j in range(X.shape[1]):

        score[i] += w[j] * X[i,j]

score

array([ 31.,  31.,  31.,  31.,  31.,  31.])

In [244]:
rowtotal = np.sum(X, axis = 1)

In [110]:
X = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
w = np.array([1,2,3,4])
y = np.array([1,2,3,4,5,6])
for i in range(y.shape[0]):

    if y[i] < 0:

        y[i] = 0

y
rowtotal = np.sum(X, axis = 1)
print(rowtotal)
print(y)

[10 10 10 10 10 10]
[1 2 3 4 5 6]


In [237]:
X = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
w = np.array([1,2,3,4])
y = np.array([1,2,3,4,5,6])
y[y<0]=0
print(y)


[1 2 3 4 5 6]


In [47]:
w = np.array([2,2,2,2])
L2norm = 0
L2norm=np.sum(np.square(w))
L2norm=np.sqrt(L2norm)
L2norm

4.0

In [24]:
m=np.array([[1,2],[3,4],[5,8]]) #3 arrays and 3 columns. if two square brakets in array then it is two dimensional
m
m.shape

(3, 2)